version: '2.2'
services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:${VERSION}
    container_name: apm01
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    env_file:
      - ./.env
    ports:
      - 8200:8200
    networks:
      - elastic
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.template.settings.index.number_of_replicas=0
    volumes:
      - ./subconfigs/apm-server.yml:/usr/share/apm-server/apm-server.yml
      - certs:$CERTS_DIR
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
networks:
  elastic:
    driver: bridge

volumes:
  certs:
    driver: local
