filebeat.inputs:
  type: log
  enabled: true
  paths:
    - /var/log/*.log

filebeat.overwrite_pipelines: true

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.logstash:
  enabled: false

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: elastic
  password: FlbljwYLuatZ4GznDx8E
  protocol: https
  ssl.certificate_authorities: ${CERTS_DIR}/ca/ca.crt
  ssl.certificate: ${CERTS_DIR}/es01/es01.crt
  ssl.key: ${CERTS_DIR}/es01/es01.key

setup.kibana:
  host: "https://kib01:5601"
  ssl.enabled: true
  ssl.certificate_authorities: ${CERTS_DIR}/ca/ca.crt
  ssl.certificate: ${CERTS_DIR}/kib01/kib01.crt
  ssl.key: ${CERTS_DIR}/kib01/kib01.key

setup.ilm.overwrite: true
setup.dashboards.enabled: true

filebeat.modules:
  - module: mongodb
    log:
      enabled: true
      var.paths: ["/var/log/mongodb/*.log"]
  - module: elasticsearch
    server:
      enabled: true
