---
version: '3'

services:
  mongodb:
    image: mongo:4.2.14
    container_name: mongodb
    restart: unless-stopped
    command: mongod --logpath /var/log/mongodb/mongod.log
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    environment:
      - security.authorization=enable
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_DATA_DIR=${MONGODB_DATA_DIR}
      - MONDODB_LOG_DIR=${MONDODB_LOG_DIR}
    volumes:
      - mongodbdata:/data/db
      - mongodblog:/var/log/mongodb/

volumes:
  mongodbdata:
    driver: local
  mongodblog:
    driver: local