version: '3.5'

services:
  selenium-hub:
    image: selenium/hub:3.12.0-boron
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - crawler

  chrome:
    image: selenium/node-chrome:3.12.0-boron
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - crawler

  crawler_taipei:
    build:
      context: ./
      dockerfile: Dockerfile.crawler
    container_name: crawler_taipei
    environment:
      - CITY_ID=1                 # the order of element in 591 website for selenium working
      - PAGE_LIMIT=300            # the max page for urls parsing
      - URL_END=9000              # the max number of houses for urls parsing
      - EXECUTED_TIME=19:51
      - CHROME_HOST=selenium-hub
      - USE_DOCKER=1              # whether use docker selenium or not
      - MONGO_HOST=mongodb
    networks:
      - crawler

    depends_on: [selenium-hub, chrome]

  crawler_new_taipei:
    build:
      context: ./
      dockerfile: Dockerfile.crawler
    container_name: crawler_new_taipei
    environment:
      - CITY_ID=3                 # the order of element in 591 website for selenium working
      - PAGE_LIMIT=300            # the max page for urls parsing
      - URL_END=9000              # the max number of houses for urls parsing
      - EXECUTED_TIME=19:51
      - CHROME_HOST=selenium-hub
      - USE_DOCKER=1              # whether use docker selenium or not
      - MONGO_HOST=elastic_gateway
    networks:
      - crawler

    depends_on: [selenium-hub, chrome]

  elastic_gateway:
    image: nginx
    container_name: elastic_gateway
    networks:
      - crawler
      - es_elastic
    volumes:
      - ./docker-manifests/subconfigs/nginx-elastic.conf:/etc/nginx/conf.d/elastic.conf
      - ./docker-manifests/subconfigs/nginx.conf:/etc/nginx/nginx.conf

    depends_on: [selenium-hub, chrome]


networks:
  crawler:
    driver: bridge
  es_elastic:
    external: true
