# Module: mongodb
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-module-mongodb.html

- module: mongodb
  #metricsets:
  #  - dbstats
  #  - status
  #  - collstats
  #  - metrics
  #  - replstatus
  period: 10s
  enabled: true
  hosts: ["mongodb:27017"]
  username: ${MONGO_INITDB_ROOT_USERNAME}
  password: ${MONGO_INITDB_ROOT_PASSWORD}
  metricsets: ["dbstats", "status", "collstats", "metrics"]


  # The hosts must be passed as MongoDB URLs in the format:
  # [mongodb://][user:pass@]host[:port].
  # The username and password can also be set using the respective configuration
  # options. The credentials in the URL take precedence over the username and
  # password configuration options.

  # Optional SSL. By default is off.
  #ssl.enabled: true

  # Mode of verification of server certificate ('none' or 'full')
  #ssl.verification_mode: 'full'

  # List of root certificates for TLS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
